### ISSUE TITLE
Order workspace list by latest uploaded

### ISSUE THREAD

**Issue by notshi** [IATI/IATI-Validator-Web#23]
![Screenshot-20210712141611-1143x261](https://user-images.githubusercontent.com/1515961/125294303-0eb0f680-e31c-11eb-83a0-5fa217d4fa17.png)

When uploading more files to the workspace, it would be very helpful if the list is updated by latest uploaded.
Currently, the list assigns it a random order and it can be difficult to find the file I've just uploaded.

**Comment by notshi** [comment]
Looks like I may have raised this issue in the wrong repo. Will raise it in the right one.

It might be useful to include a link to https://github.com/IATI/IATI-Validator-Actual for such things in the readme of this repo as there are 4 validator type repos, one of which is archived. Or pin it to the IATI main repo?

**Comment by nosvalds** [comment]
Hi @notshi, we've implemented this suggestion as part of version 2 of the Validator which we are planning to launch in September.

I'm going to close this issue now.
