### ISSUE TITLE
Files that fail to download get a schema valid message

### ISSUE THREAD

**Issue by stevieflow** [IATI/IATI-Validator-Web#476]
**Brief Description**

For some reason, UNOPS data files cannot be download by the validator (and other services) - to do with an SSL issue on their server: 

https://iativalidator.iatistandard.org/organisation/unops

![IATI-Validator](https://user-images.githubusercontent.com/1209944/170201939-e4d8512d-f26a-464f-af45-e2f22918f78c.png)

That seems fine and expected.

However, there seems to be a route through to pages that give conflicting information - when viewing validation on activities, via d-portal:

https://d-portal.org/ctrack.html#view=act&aid=41AAA-23123-001 - leads to 

https://iativalidator.iatistandard.org/view/dqf/files/12a7638d-fd68-4909-84a4-7c9c9c92eba7

![IATI-Validator (1)](https://user-images.githubusercontent.com/1209944/170202364-45c5cb17-254b-4a3e-b73b-aa7af4373454.png)

The actual activity XML fails validation *a lot* - but it seems that the validator is caught out , as it has no data to test

Hopefully that is helpful - I stress the original issue starts with the publisher.  Closing this looophole might be useful...

**Severity**
Low

**Issue Location**

https://d-portal.org/ctrack.html#view=act&aid=41AAA-23123-001 - leads to 

https://iativalidator.iatistandard.org/view/dqf/files/12a7638d-fd68-4909-84a4-7c9c9c92eba7

**Steps to Reproduce**

https://d-portal.org/ctrack.html#view=act&aid=41AAA-23123-001 - l

Click IATI validator link to 

https://iativalidator.iatistandard.org/view/dqf/files/12a7638d-fd68-4909-84a4-7c9c9c92eba7

**Expected Results/Behaviour**

Invalid data report - or message to say the data file is not accessible

**Actual Results/Behaviour**

The activity is rendered as being schema valid - but (my guess) is that the validator hasnt actually been able to check it

cc/ @notshi @xriss

**Comment by nosvalds** [comment]
Hi @stevieflow this is resolved now with the new version of the Validator [v2.5.0](https://github.com/IATI/validator-web/releases/tag/v2.5.0)

<img width="737" alt="image" src="https://user-images.githubusercontent.com/60047271/202209178-a3dbe4fb-2f31-45ef-b1c3-fd83b3352ec3.png">


https://validator.iatistandard.org/report/jica-389_2015

![image](https://user-images.githubusercontent.com/60047271/202209501-93b251f0-d403-4fe7-aa3f-a88fb506d806.png)

**Comment by stevieflow** [comment]
Nice work - thanks @nosvalds !
